# baseイメージ
FROM php:7.2-fpm
# ローカルのphp設定ファイルをコンテナ内に配置
COPY php.ini /usr/local/etc/php/

# 必要な物インストール
RUN apt-get update && apt-get install -y 
RUN apt-get install -y zlib1g-dev mariadb-client
RUN docker-php-ext-install zip pdo_mysql

# Composerインストール
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

# Node.jsインストール
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN npm install --save-dev @babel/core @babel/preset-env
RUN npm install css-loader -D

# Composerの設定
ENV COMPOSER_HOME /composer

# phpの設定
ENV PATH $PATH:/composer/vendor/bin